# a generator is a class with a function generate, which takes a parameter
# size and returns a string of length size which was generated by the model
class Generator:
    def generate(self, size):
        pass