/**
// this script scrapes the files generated by skyperious and makes
// a json with all the posts
// to run it, paste the contents in the Chrome Developer console and hit Enter
// it will then prompt you to save the .json file with the result
*/

author_td = document.querySelectorAll('td.author')
messages=[]
for(var i=0;i<author_td.length;i++) {
    messages.push(author_td[i].parentElement)
}
par=[]
for(var i=0;i<messages.length;i++) {
    n={}
    a=author_td[i].parentElement
    n.author=a.children[0].title
    n.id=a.children[0].id
    n.message=a.children[2].children[0].innerHTML
    n.time=a.children[3].title
    par.push(n)
}

(function(console){
    console.save = function(data, filename){
        if(!data) {
            console.error('Console.save: No data')
            return;
        }

        if(!filename) filename = 'console.json'

        if(typeof data === "object"){
            data = JSON.stringify(data, undefined, 4)
        }

        var blob = new Blob([data], {type: 'text/json'}),
            e    = document.createEvent('MouseEvents'),
            a    = document.createElement('a')

        a.download = filename
        a.href = window.URL.createObjectURL(blob)
        a.dataset.downloadurl =  ['text/json', a.download, a.href].join(':')
        //only god knows what this function does
        e.initMouseEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null)
        a.dispatchEvent(e)
    }
})(console)

console.save(par)